### PR TITLE
Introduce SearchBundle recipe

### PR DESCRIPTION
**Pull request by julienbourdeau**
| Q             | A
| ------------- | ---
| License       | MIT

Inspired by Symfony Flex and Symfony4, I have rewritten the [Algolia Bundle for Symfony](https://github.com/algolia/search-bundle). We talked with Nicolas about adding it to the official recipes, that's why I'm opening this PR.
Note that the package is in Beta2, so you shouldn't merge it yet but I wanted to start the conversation.

The main reason behind the rewrite was to improve the developer experience and to make it more extensible. You can get started with 5 lines of YAML. Also, you can use this package with another search engine, if you write the driver for it :)
You can find out more about the package here: https://discourse.algolia.com/t/introducing-the-new-algolia-search-bundle-for-symfony/3842

Any feedback about the package is very welcome.

### CODE REVIEW

**Comment by Nyholm** [comment]
Wow, That is a great bundle. I will try it out in one of my projects. I will look at the bundle more closely later. 

The recipe looks good. But Im hesitant about putting it in the official repo.

**Comment by Nyholm** [comment]
This PR has been sitting for a while now. Could you make the same PR to contrib so people can start to use this recipe whilst this PR is in review?

**Comment by weaverryan** [comment]
I think that's a good idea. We don't mean to stall this, but it's possible that the core members don't have experience with the bundle. We can merge it immediately in contrib, people can use it, and the community can validate it :)

**Comment by julienbourdeau** [comment]
Yeah I understand. I should publish final version and nice doc today. 
I can open a new PR in contrib but I hope a core member can have a look at the bundle and we can discuss merging it here. I understand that to accept it here, core members need to understand and try it, which takes some time :)

**Comment by fabpot** [comment]
We have rules to accept a bundle in the main repository. I don't think this bundle qualifies. I would contribute it first on the contrib repository.

**Comment by julienbourdeau** [comment]
I understand that we need some more history and feedbacks. I hope the bundle it will make it to this repository one day. 🤞 
I opened this PR on contrib, to update the Algolia recipe: https://github.com/symfony/recipes-contrib/pull/244

Thank you all for your comments.

**Comment by fabpot** [comment]
Thank you.

**Pull request closed without merging**
