### PR TITLE
Add Mobyt Notifier recipe

### PR DESCRIPTION
**Pull request by Deamon**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#13606 / symfony/symfony#36648

### CODE REVIEW

**Comment by YaFou** [comment]
The file shouldn't be in the folder `5.2`?

**Comment by fabpot** [comment]
Indeed.

**Comment by Deamon** [comment]
@fabpot @YaFou, done :)

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Pull request merged**
