### PR TITLE
Added notifier bridge recipes

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...    

I've started this PR with the Slack notifier (also the most "complex" as 5.0 and 5.1 don't have the same DSN pattern), but I need help for the other ones:

- [ ] Firebase
- [x] Mattermost
- [x] Nexmo
- [x] OvhCloud
- [x] RocketChat
- [x] Sinch
- [x] Telegram
- [x] Twilio

Who wants to help? Comment here and send me a PR on this PR.

### CODE REVIEW

**Comment by simivar** [comment]
@fabpot I've created [PR for Nexmo](https://github.com/symfony/recipes/pull/754).

**Comment by simivar** [comment]
@fabpot I've created PRs for all Notifiers except *Firebase*. From what I see in [FirebaseTransportFactory](https://github.com/symfony/firebase-notifier/blob/master/FirebaseTransportFactory.php) it gets `user` and `password` but makes string concatenation and assigns it to `token` variable. Because of that, I don't know which DSN is the correct one:

```
FIREBASE_DSN=firebase://USER:PASSWORD@default
```
or
```
FIREBASE_DSN=firebase://TOKEN@default
```
or
```
FIREBASE_DSN=firebase://TOKEN_PART_1:TOKEN_PART_2@default
```

**Comment by fabpot** [comment]
Thank you @simivar, you've done a great job!

**Comment by fabpot** [comment]
Regarding Firebase, I don't know either, can you ping the creator of the bridge on the original PR?

**Comment by simivar** [comment]
@jeroeny could you please help me with Firebase DSN? My [question is in this comment](https://github.com/symfony/recipes/pull/753#issuecomment-612684237).

**Comment by Jeroeny** [comment]
@simivar Yes, it's one token, so I'd go with:
```
FIREBASE_DSN=firebase://TOKEN@default
```

**Comment by simivar** [comment]
@Jeroeny thank you! 

@fabpot [the last PR is here](https://github.com/symfony/recipes/pull/761).

**Pull request merged**
