### PR TITLE
Rely on defaults for doctrine mapping types

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

Needs https://github.com/symfony/symfony/pull/42054 to be released before merging.

### CODE REVIEW

**Comment by jrushlow** [comment]
We're wrapping up attribute support in MakerBundle now in https://github.com/symfony/maker-bundle/pull/920 We should have this merged and released pretty quick.

**Comment by fabpot** [comment]
@jrushlow Correct if I'm wrong, but this change is not a requirement. I understand that it would be better, but as I said, I'm afraid that it will break a lot of things. I know for instance that the Symfony book will break instanenaously.
I would recommend waiting for 5.4 to be released so that we can have a version of the book with support for the new maker bundle.

**Comment by weaverryan** [comment]
> I would recommend waiting for 5.4 to be released so that we can have a version of the book with support for the new maker bundle.

That makes sense to me. Indeed, this recipe is not a blocker for MakerBundle. Once it *is* merged, we'll just need to update some MakerBundle tests - no big deal :).

**Comment by weaverryan** [comment]
Is it safe to merge this PR now? Without it, if you start a brand new Symfony 6 project / PHP 8, etc, you still get annotation-powered entities instead of attributes.

**Review by chalasr — APPROVED** [review]

**Review by derrabus — APPROVED** [review]

**Review by Tobion — APPROVED** [review]

**Pull request merged**
