### PR TITLE
Add recipe for symfony/iqsms-notifier

### PR DESCRIPTION
**Pull request by OskarStark**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#14555

cc @alexandrbarabolia

refs https://github.com/symfony/symfony/pull/39096

### CODE REVIEW

**Comment by OskarStark** [comment]
@fabpot any clue why this does not pass?

Ah maybe the repo is not yet available? Or the release not created on packaging?

**Comment by OskarStark** [comment]
friendly ping @fabpot

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Review by fabpot — APPROVED** [review]

**Review by fabpot — COMMENTED** [review]
merge now

**Pull request merged**
