### PR TITLE
PHPUnit: use XSD schema from vendor

### PR DESCRIPTION
**Pull request by mhujer**
| Q             | A
| ------------- | ---
| License       | MIT

Instead of having to manually downloading the XSD to get completion (It available in Alt+Enter menu in PhpStorm), we can use the XSD directly from the installed package.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Does this work when the simple-phpunit script from the bridge is used?

**Comment by mhujer** [comment]
Ups, maybe not. I'm personally not using it, so I will try it and verify this.

**Comment by Pierstoval** [comment]
By the way, integration of the phpunit bridge in PHPStorm is really cumbersome, so at least keeping this canonical xsd reference is the best option IMO

**Comment by mhujer** [comment]
My change does not work with simple-phpunit, because it installs PHPUnit separately into 
`bin/.phpunit/phpunit-6.5/`, so I'm closing this PR.

**Pull request closed without merging**
