### PR TITLE
Update console require file

### PR DESCRIPTION
**Pull request by noniagriconomie**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...    

Hi,
cf https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.4/public/index.php#L7 (the other php symfony entry point)

should we do the same here? (or maybe I miss something)

Thank you,

### CODE REVIEW

**Comment by jvasseur** [comment]
The bootstrap file reads values in `$_SERVER`, this means it needs to be included after we read the `--end` and `--no-debug` options (that modify the content of `$_SERVER`.

**Comment by noniagriconomie** [comment]
@jvasseur thank you for the reply,
but why this difference with the other file `index.php` which does not used `$_SERVER`?

**Comment by jvasseur** [comment]
The difference comes from those lines :
https://github.com/symfony/recipes/blob/5f8acedd41d584611b2422aa3d4d66f97c70c3f2/symfony/console/4.4/bin/console#L22-L28

They needs to be executed between loading the autoloader and loading the bootstrap file. Since they don't exists in `index.php` we can directly load the bootstrap file.

**Comment by noniagriconomie** [comment]
oki understood, lets close this then :)

**Pull request closed without merging**
