### PR TITLE
List .preload.php in .gitignore

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

Maps to https://github.com/symfony/symfony/pull/38063

### CODE REVIEW

**Review by yceruto — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Review by fabpot — APPROVED** [review]
merge now

**Comment by CthulhuDen** [comment]
But what about 5.1, where you''ve added the file?

**Comment by stof** [comment]
@CthulhuDen the file also exists in 4.4.14+. And this file is generated by the cache warmup, so ignoring it from the git repo is OK.

**Comment by CthulhuDen** [comment]
But why 5.1 recipe for .gitignore doesn't include this file?

**Comment by nicolas-grekas** [comment]
@CthulhuDen check https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/manifest.json

**Comment by CthulhuDen** [comment]
Oh, I see. Sorry for the bother. It's just one of my projects suddenly got this file (and of cause it did not magically add it to existing .gitignore).

**Comment by stof** [comment]
> and of course it did not magically add it to existing .gitignore

you might need to run `composer symfony:sync-recipes` to apply the new version of the recipe.

**Pull request merged**
