### PR TITLE
symfony/webpack-encore: bump to ^4.0.0, add peer dependencies webpack, webpack-cli, @babel/core and @babel/preset-env

### PR DESCRIPTION
**Pull request by Kocal**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | n/a

Related to https://github.com/symfony/webpack-encore/pull/1142, ping @weaverryan

### CODE REVIEW

**Comment by weaverryan** [comment]
This looks good - I've just made it a draft PR, since we'll need to release Encore first. But when we do, this PR is ready to go - thanks :)

**Comment by weaverryan** [comment]
Actually, we also need to remove pushing the `@babel/plugin-proposal-class-properties` plugin: https://github.com/symfony/recipes/blob/96d11c2e2ed2a33a796740ed47de0d6d25263fe8/symfony/webpack-encore-bundle/1.10/webpack.config.js#L49

**Comment by Kocal** [comment]
Done @weaverryan, also tell me WYT about the `webpack.config.js` plz 🙏🏻 

I will let you mark the PR ready for review.

**Review by weaverryan — APPROVED** [review]
4.0 is released - https://github.com/symfony/webpack-encore/releases/tag/v4.0.0 - this is ready to go

**Review by kbond — APPROVED** [review]

**Comment by Kocal** [comment]
Yay

**Pull request merged**
