### PR TITLE
Define services and routes in App\Kernel

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

Going one step further than #765, we can just drop the `config/services.yaml` and `config/routes.yaml` files entirely.

### CODE REVIEW

**Comment by BoShurik** [comment]
With this change part of the container and router configuration will be in `src` but semantically should be in `config`

**Comment by fabpot** [comment]
Not sure I like this change. It makes configuration less visible and buried into a PHP class.

**Review by fabpot — CHANGES_REQUESTED** [review]
Having thought a bit more about this one, and I definitely don't like this change. :-1: for me.

**Comment by nicolas-grekas** [comment]
Sorry, I posted this from 2025, I forgot we were still in 2021 ;)

**Pull request closed without merging**
