### PR TITLE
Update spacing of doctrine yml files

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...

Use symfony coding standard of yml files with 4 spaces.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
That could be worth a new check in the qa action. Would you like having a look?

**Comment by alexander-schranz** [comment]
@nicolas-grekas how can we achieve this. Think the `lint:yaml` of symfony does not care about the yaml style? Are there any other tools used in symfony todo this?

**Comment by alexander-schranz** [comment]
@fabpot do we need to change this offset value? https://github.com/symfony/flex/pull/788#discussion_r697849436

**Comment by OskarStark** [comment]
Yamllint binary can check

**Comment by nicolas-grekas** [comment]
Reverting as this 2-spaces indent was on purpose, docker-compose rulez.

**Pull request merged**
