### PR TITLE
[doctrine-bundle] add single quotes for DATABASE_URL

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Fixes https://github.com/symfony/symfony/issues/26056

**Comment by Nyholm** [comment]
Are you sure you want single quotes and double quotes?

**Comment by nicolas-grekas** [comment]
The doubles are for json, the single for .env.

**Comment by fabpot** [comment]
This must be reverted as this is wrong. Flex manages escaping depending on the context (XML, .env, ...).

**Comment by Nyholm** [comment]
There is an open PR: https://github.com/symfony/recipes/pull/359

**Pull request merged**
