### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by 94noni**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...

default mandatory props

### CODE REVIEW

**Comment by stof** [comment]
`version` is not actually mandatory when you don't plan to publish a package in the registry.

**Comment by 94noni** [comment]
hum indeed @stof 
should I close or only remove the `version` part?

**Comment by stof** [comment]
IIRC, the name is also optional when you don't publish it. It is only required when you want to submit to the registry. So I would close this PR.

**Comment by 94noni** [comment]
@stof understood, thx for your time :)

**Pull request closed without merging**
