### PR TITLE
Recommend NPM instead of Yarn

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

/cc @weaverryan @dunglas

### CODE REVIEW

**Review by wouterj — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Comment by melroy89** [comment]
Just for info. I would like to see the demo also move to NPM (package-lock.json): https://github.com/symfony/demo

**Comment by stollr** [comment]
I'm curious as to why the recommendation was changed from Yarn to NPM. Are there any information?

**Comment by stof** [comment]
Back when we started this recommendation (when introducing webpack-encore), yarn was strictly superior to npm, mostly thanks to having a proper lockfile (at that time, npm did not have package-lock.json but only the shrinkwrap mechanism) and being faster.
Since then, npm has caught up on those fronts. And it has the big benefit of being installed by default when you install node, which requires 1 less step.
Note however that webpack-encore is not dropping support for yarn (it tests compatibility with several package managers) and so you can keep using yarn if you prefer (or pnpm for that matter)

**Comment by stollr** [comment]
This makes sense. Thanks for your explanation.

**Pull request merged**
