### PR TITLE
recipe for Messenger monitor bundle

### PR DESCRIPTION
**Pull request by nikophil**
Q | A
-- | --
License | MIT

recipe for the bundle https://github.com/SymfonyCasts/messenger-monitor-bundle/

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@nikophil this PR is in draft btw, please let us know you intentions about it.

**Comment by lyrixx** [comment]
The bundle is very wip. Is it the right place for wip projets?

**Comment by fabpot** [comment]
Let's close for now. I think it should part of recipes-contrib at first.

**Pull request closed without merging**
