### PR TITLE
base.html.twig: remove optional tags

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| License       | MIT

Remove optional tags according to [Google Best Practices](https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags) and [the HTML5 spec](https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission).

Having a minimalist starting file is more in the spirit of Flex.

### CODE REVIEW

**Comment by weaverryan** [comment]
I'm worried it'll be confusing for many users. It doesn't *look* like an HTML page anymore - so for many users (me included) I'd be thinking "what is this?" and "where should I put my content?"

So, I'm not sure it's worth it... 🤔

**Comment by dunglas** [comment]
It's our duty to educate our users to the modernized frontend stack, and the new features of HTML, JS, CSS :)
Writing HTML like that is a recommended practice for a while, implemented by all browsers and easier when you get used to it.

**Comment by stof** [comment]
I'm -1 for that, as it makes usage of the layout much harder. Rules about tags being optional heavily depend about what comes after them and what comes as their first child. As soon as you have a block allowing to change this content, you can be sure it is actually optional in the final output.

And btw, this would break the web debug toolbar, which won't be able to detect this as a full page where it should get injected.

**Comment by stof** [comment]
And this would also break testing with the BrowserKit component, as PHP's DomDocument API does not support these rules.

**Comment by Pierstoval** [comment]
This would also break the web debug toolbar which adds the script when it sees `</body>` in a Response.

**Comment by fabpot** [comment]
Let's close.

**Pull request closed without merging**
