### PR TITLE
Tweak letter case of "SQLite" and change article "a" -> "an"

### PR DESCRIPTION
**Pull request by bocharsky-bw**
| Q             | A
| ------------- | ---
| License       | MIT

A few minor tweaks

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Wow, Symfony Bot rocks :)

**Comment by javiereguiluz** [comment]
Could a native English speaker please confirm this change? Google says that "a" is more commonly used:

a an

**Comment by bocharsky-bw** [comment]
When spelling SQL (`[ ˈes kjˈuː w̆ˈel ]`) with Google translate - it starts with a vowel `e`, so I'll be surprised if I'm wrong

**Comment by bocharsky-bw** [comment]
And Ryan uses "an SQL" in KnpU screencasts 😇
https://knpuniversity.com/screencast/php-ep3/sql-injection-prepared-statements

**Comment by ogizanagi** [comment]
https://sqlite.org/quickstart.html itself uses `an SQLite database`

**Pull request merged**
