### PR TITLE
remove unsued mysql configuration

### PR DESCRIPTION
**Pull request by abdounikarim**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...    

Hello,

I just remove old mysql configuration.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I think we should keep these lines because they're critical when one wants to use MySQL.

**Comment by abdounikarim** [comment]
@nicolas-grekas we can just comment them ?

**Comment by fabpot** [comment]
When not using MySQL, is there any issues with these lines?

**Comment by nicolas-grekas** [comment]
They're ignored when not using mysql.

**Pull request closed without merging**
