### PR TITLE
Partner GH action workflow for updating RECIPES.md

### PR DESCRIPTION
**Pull request by weaverryan**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | none

To be merged after #1078.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
[Oops](https://github.com/symfony/recipes/runs/6241616892):

```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Required status check "call-qa / Run checks" is expected. At least 2 approving reviews are required by reviewers with write access.        
To https://github.com/symfony/recipes
 ! [remote rejected] main -> main (protected branch hook declined)
```

**Comment by nicolas-grekas** [comment]
There's something strange also: this workflow will run on "push" to "main", and it will push to main. There's a circular loop here. It will likely stop by itself since the RECIPES.md file won't have any changes to be committed, but then, I'm wondering if the action won't fail because either "commit" or "push" might return a non-zero status code because of this empty diff.

**Comment by nicolas-grekas** [comment]
We should maybe push to flex/main instead of main. That'd fix both issues.

**Comment by weaverryan** [comment]
I’ll work on that :). I thought about the circular loop, but it didn’t actually happen in real life - my theory is that a push from GH actions doesn’t trigger another action. But, pushing to flex/main seems totally fine.

**Pull request merged**
