### PR TITLE
Create recipe for the Apache pack

### LINKED ISSUE #190: Recipe for "public/.htaccess" file
I can't find a recipe that would install default ".htaccess" file (see https://github.com/symfony/symfony-standard/blob/3.3/web/.htaccess) into "public" folder so that all mod-rewrite urls would still work.

Without it after fresh install I'm getting 404 on any route access (including routes generated by Web Profiler).

### PR DESCRIPTION
**Pull request by Pierstoval**
| Q             | A
| ------------- | ---
| License       | MIT

Fixes #190

### CODE REVIEW

**Comment by fabpot** [comment]
I think it belongs to `recipes-contrib`. I would certainly not recommend using Apache.

**Comment by Pierstoval** [comment]
Users will not be able to use the alias then, and even though the Symfony team doesn't recommend apache, maybe providing an "official" apache config could be a better option to say _"We don't recommend it, but here's the way to do it if you really want it"_.

WDYT?

**Comment by xabbuh** [comment]
IMO even when using Apache, using a `.htaccess` file is not the recommend approach, but the configuration should be done on the vhost level instead.

**Comment by weaverryan** [comment]
The alias is not a huge deal... it *is* kinda nice, but people will need to read the docs anyways to find this. Let's put it on contrib for now.

There is already an identical PR waiting in contrib - symfony/recipes-contrib#164

**Comment by stof** [comment]
Closing this, as @fabpot explicitly said in the issue that he wants this recipe to live in contrib.

**Pull request closed without merging**
