### PR TITLE
Update Webpack Encore version

### PR DESCRIPTION
**Pull request by codedmonkey**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by fabpot** [comment]
Do we really want forbid people to use older versions? In any case, composer will always install the latest one. So, what's the point?

**Comment by weaverryan** [comment]
Yea, that's fine with me - there's really no point.

**Comment by BoShurik** [comment]
Version `0.19.0` does not satisfy `^0.17.0`. Every time after applying recipe I should change constraint

**Comment by fabpot** [comment]
Ah, we are at version < 1.0. Reopening then.

**Pull request merged**
