### PR TITLE
[twig/extra-bundle recipe] New recipe

### PR DESCRIPTION
**Pull request by mareksuscak**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | n/a

I got bitten by this one. Most packages have a corresponding official recipe but not this one and its installation instructions are not stated anywhere (at least I did not find them). I think it might be worth it adding it as a replacement for the old cssinliner package.

### CODE REVIEW

**Comment by stof** [comment]
This recipe is useless. As the type of the package is `symfony-bundle`, Flex already automatically registers the bundle by auto-generating exactly that recipe.

**Comment by stof** [comment]
btw, the CI reports it.

**Comment by mareksuscak** [comment]
> This recipe is useless. As the type of the package is symfony-bundle, Flex already automatically registers the bundle by auto-generating exactly that recipe.

For whatever reason `composer require twig/extra-bundle` did not add the bundle to `bundles.php` file on my end. I have tried `composer remove twig/extra-bundle` and re-required the bundle but it did not help. Am I not doing it right? (apologies if it's a silly question, PHP is not my main area of expertise)

> btw, the CI reports it.
Don't get me wrong but it came across as a fairly rude comment. I did see that the check was failing, of course. For context, I came across the old `cssinliner-extension` recipe that's essentially a clone of the one I'd created and that made me think that `twig/extra-bundle` is missing.

**Comment by xabbuh** [comment]
For me this works without the recipe:

```
$ composer require twig/extra-bundle
Using version ^3.0 for twig/extra-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Package operations: 5 installs, 0 updates, 0 removals
  - Installing twig/twig (v3.0.3): Loading from cache
  - Installing symfony/translation-contracts (v2.0.1): Loading from cache
  - Installing symfony/twig-bridge (v5.0.7): Loading from cache
  - Installing symfony/twig-bundle (v5.0.7): Loading from cache
  - Installing twig/extra-bundle (v3.0.3): Loading from cache
Writing lock file
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony operations: 2 recipes (63a0bf7eeffbd8370e433b79504764eb)
  - Configuring symfony/twig-bundle (>=5.0): From github.com/symfony/recipes:master
  - Configuring twig/extra-bundle (>=v3.0.3): From auto-generated recipe
Executing script cache:clear [OK]
Executing script assets:install public [OK]

Some files may have been created or updated to configure your new packages.
Please review, edit and commit them: these files are yours.
```

and:

```
$ cat config/bundles.php 
<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
];
```

**Comment by mareksuscak** [comment]
That's great. I don't know why it's not working on my end. However, in my case, I already had the twig bundle installed and therefore I only needed to add twig-extra. I wonder if it makes any difference?

**Pull request closed without merging**
