### PR TITLE
Remove debug for default PHPUnit config

### PR DESCRIPTION
**Pull request by fabpot**
| Q             | A
| ------------- | ---
| License       | MIT

### CODE REVIEW

**Comment by stof** [comment]
Running tests in no-debug mode has the benefit of running tests much faster (as you don't need to check the cache freshness in each test, while the code would not have changed).
But this has one drawback: it requires you to have either a fresh cache for the test env or no cache. If you have an stale cache, tests will run using it (and will likely fail).

Here is how I solved it at Incenteev:

```php
namespace Incenteev\Tests\Util;

use Symfony\Component\Filesystem\Filesystem;

class CacheClearer
{
    public function clearCache()
    {
        if (getenv('INCENTEEV_KEEP_CACHE')) {
            return;
        }

        $filesystem = new Filesystem();

        $filesystem->remove($this->getCacheFolders());
    }

    private function getCacheFolders()
    {
        return array(
            __DIR__.'/../../../var/api-cache/test',
            __DIR__.'/../../../var/api-cache/behat',
            __DIR__.'/../../../var/cache/test',
            __DIR__.'/../../../var/cache/behat',
        );
    }
}
```

And then, my PHPUnit bootstrap script is this:

```php
require __DIR__.'/../app/autoload.php';

(new \Incenteev\Tests\Util\CacheClearer())->clearCache();
```

This ensures that a developer running tests locally does not have a stale cache (the env variable `INCENTEEV_KEEP_CACHE` allows to avoid clearing the cache on CI, where I know that the cache created by the previous CI command is not stale).

**Comment by fabpot** [comment]
There is another issue with enabling debug, and that's a bunch of logs on the console. Maybe that should be fixed as well. /cc @dunglas

**Comment by dunglas** [comment]
@fabpot maybe can we just remove the `logger` service in test mode?

**Comment by fabpot** [comment]
@dunglas Makes sense. How is it configured for the console (do we have the same issue)?

**Comment by Pierstoval** [comment]
Just by using this and enabling debug mode manually in certain tests (that need profiler or that test debug-related services) I made my tests run 3 times faster 👍

**Comment by dunglas** [comment]
@fabpot see #248.

For the console, it's ok to write logs on stderr isn't it?

**Comment by fabpot** [comment]
@dunglas Having logs entangled with some "real" output always looks like a bug to me.

**Comment by nicolas-grekas** [comment]
What about setting the SHELL_VERBOSITY env var instead?

**Comment by fabpot** [comment]
closing in favor of #281

**Pull request closed without merging**
