### PR TITLE
Add Discord notifier recipe

### PR DESCRIPTION
**Pull request by mpiot**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#13558   symfony/symfony#36475

Add a recipe for the discord notifier

### CODE REVIEW

**Review by OskarStark — APPROVED** [review]

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Comment by OskarStark** [comment]
What is wrong here @fabpot 🤔

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Review by fabpot — APPROVED** [review]
merge now

**Comment by OskarStark** [comment]
Thanks!

**Pull request merged**
