### PR TITLE
Add SensioGeneratorBundle recipe

### PR DESCRIPTION
**Pull request by maidmaid**
| Q             | A
| ------------- | ---
| License       | MIT

cf https://symfony.com/doc/master/bundles/SensioGeneratorBundle/index.html

### CODE REVIEW

**Comment by sstok** [comment]
I think dev would be enough, but I don't use this bundle anymore :)

**Comment by weaverryan** [comment]
There will be updates made / a different generator in time for 4.0. When we have that, we can open a recipe, because I agree with @maidmaid that having an alias is a great idea.

So -1 for me, but only because we will do it soon, but not for this bundle.

**Comment by maidmaid** [comment]
@sstok I agree with you, but `test` env accords to the current documentation.

@weaverryan Yes, an alias is useful. Moreover, this recipe prevents to enable this bundle with `all` envs, but only for `dev` (and `test`) env.

**Comment by fabpot** [comment]
Closing as we will have another solution for Symfony 4/Flex.

**Comment by aik099** [comment]
@fabpot , what solution, any blog post/documentation page on that?

**Pull request closed without merging**
