### PR TITLE
Wire symfony/psr7-pack

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

Fix https://github.com/symfony/psr-http-message-bridge/pull/94
Fix https://github.com/symfony/recipes/pull/910
Fix https://github.com/symfony/recipes/issues/909

Requires registering https://github.com/symfony/psr7-pack on packagist /cc @fabpot 

/cc @derrabus @Nyholm 

I think this approach good enough: less code to maintain and solves the issue of keeping things decoupled.
See discussions on the linked PRs.

### CODE REVIEW

**Comment by stof** [comment]
I don't think that works, actually. As packs are unpacked automatically by Flex, you won't have any recipes to apply for them. Packs are only getting aliases in their recipes, not install-time content

**Review by Nyholm — CHANGES_REQUESTED** [review]
The manifest `psr-http-message-bridge/2.1/manifest.json` is now invalid. 

Did you really mean to move the `config/packages/psr_http_message_bridge.yaml`?

**Comment by nicolas-grekas** [comment]
> The manifest psr-http-message-bridge/2.1/manifest.json is now invalid.

It's been moved to `psr7-pack` also, there is no recipe for `psr-http-message-bridge` anymore in this PR. This follows https://github.com/symfony/recipes/issues/909#issuecomment-795446904

**Review by Nyholm — APPROVED** [review]
Thank you

**Review by fabpot — APPROVED** [review]

**Pull request merged**
