### PR TITLE
Add symfony/serializer-pack

### PR DESCRIPTION
**Pull request by dunglas**
| Q             | A
| ------------- | ---
| License       | MIT

See also https://github.com/dunglas/serializer-pack/

### CODE REVIEW

**Comment by stof** [comment]
The github repo should be moved to the symfony organization IMO (and it needs to be registered on Packagist)

**Comment by dunglas** [comment]
@stof indeed it's the plan (I've added @fabpot and @nicolas-grekas as owners, they should be able to transfer it).

**Comment by fabpot** [comment]
I've just created the package and tagged version 1.0

**Comment by fabpot** [comment]
@symfony-flex-server review

**Comment by Nyholm** [comment]
Im testing this out and I get the following error
screen shot 2017-11-29 at 21 26 44

I guess it is a temporary thing with symfony.sh

**Comment by Nyholm** [comment]
It was a temporary thing. All good now

**Comment by stof** [comment]
Maybe it was because the PR was merged already when you tried it

**Pull request merged**
