### PR TITLE
Use static app callable for the new Runtime component

### PR DESCRIPTION
**Pull request by SerheyDolgushev**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | N/A

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
They are already static because they're not declared in a method.

**Comment by SerheyDolgushev** [comment]
Sorry, but the anonymous function should use `static` keyword to be static. If the function is not declared as a method it does not make it static: https://www.php.net/manual/en/functions.anonymous.php#functions.anonymous-functions.static

**Comment by nicolas-grekas** [comment]
yes it does, see eg https://3v4l.org/FT3gl

**Comment by nicolas-grekas** [comment]
I suppose you mean static as in not allowing rebinding: https://3v4l.org/5fQMn
This makes zero difference here as there is no `$this`.
Let's save some boilerplate.

**Comment by Nyholm** [comment]
Thank you for this @SerheyDolgushev 

Does this PR has an impact in performance, usability or any other way? Or is it just to please some good practices?

**Comment by SerheyDolgushev** [comment]
@Nyholm 
Actually, this OR impact on performance can be neglected. Also, it has no effect on usability. 
In this case, we have anonymous functions that are not expecting to have any instance to be bind to it. And according to https://www.php.net/manual/en/functions.anonymous.php#functions.anonymous-functions.static such kind functions should use `static` keyword. So personally I think this PR makes the code a bit more cleaner.

**Comment by Nyholm** [comment]
Since this PR is only about code style (subjective opinion) I prefer to keep things the way it is. Simply because it is less code and my subjective opinion believe the current code is more clean. 

Thank you for the references.

**Comment by nicolas-grekas** [comment]
Resubmitted as #984, with benchmarks this time!

**Pull request closed without merging**
