### PR TITLE
Property info

### PR DESCRIPTION
**Pull request by Saphyel**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | https://symfony.com/doc/current/components/property_info.html

### CODE REVIEW

**Comment by stof** [comment]
I don't think that's necessary. The default value of the `enabled` flag is a smart default depending on whether the package is installed.

**Comment by Saphyel** [comment]
I found sometimes with prod config that is not always enabled. In dev mode is as you said

**Comment by stof** [comment]
@Saphyel in prod mode, be careful to clear your cache. But the logic for the default is the same.

**Comment by nicolas-grekas** [comment]
Closing as explained by @stof

**Pull request closed without merging**
