### PR TITLE
Improve SymfonyFrameworkBundle Kernel.php

### PR DESCRIPTION
**Pull request by yyaremenko**
| Q             | A
| ------------- | ---
| License       | MIT

This commit makes Kernel.php look more professional for v4.2. If it's okay for you, I will update the Kernel.php for v3.3 in the same manner.

### CODE REVIEW

**Comment by B-Galati** [comment]
There is no such thing called professional code. Just choices to be made in a given context. 

IMHO this proposal just make things more complicated that they need to be for no good reason.

**Comment by yyaremenko** [comment]
No, there **is** such thing called professional code, regardless of programming language. Like, using constants with explanatory names for repetitive strings, avoiding copy-and-paste (keeping to DRY principle), making one method doing one thing only etc. But hey, you are the contributor and, I guess, you have the better vision of the code.

Thanks for the reply and have a nice day.

**Comment by yyaremenko** [comment]
(you are welcome to decline the PR)
thanks.

**Comment by B-Galati** [comment]
Best practices must not be blindly applied. There is a difference between DRY and copy/paste.

Please read this great article: https://web-techno.net/dry-principle-explained/

Regarding your PR, I do not decide anything, I gave my opinion because I wanted to.

**Comment by yyaremenko** [comment]
Thank you for the clarification, I am not quite aware of PR decision makers for this repository. Also, thank you for the article. Still I am afraid I don't quite understand how creation of unneeded abstract classes relates to the changes I offer, as my changes have nothing common with the problem described.

**Comment by yyaremenko** [comment]
> this doesn't qualify as an improvement, it's just a different opinion.

1. renaming a constant from CONFIG_EXTS to a more descriptive name CONFIGS_POSSIBLE_EXTENSIONS 

is a different opinion, not a code improvement, no way

2. moving repetitively used string 'glob' to a constant with a descriptive name RESOURCE_TYPE_GLOBAL

the same purpose constant CONFIG_EXTS was fine though, but the constant I added is a 'different opinion', okay

3. instead of calling $this->getProjectDir().'/config/bundles.php' twice, a dedicated method returning this path is created getBundlesFilePath()

so, using a single entry point instead of copy-and-pasting is a 'different opinion', okay

4. instead of calling $this->getProjectDir().'/config' twice, a dedicated method returning the path is created

single entry point instead of copy-and-pasting is a 'different opinion', yeah, yeah

5. instead of copy-and-pasting code signature as follows
ob->doSomething(x, valueA, y, z);
ob->doSomething(x, valueB, y, z);
ob->doSomething(x, valueC, y, z);

a dedicated method was created, iterating over vallueA, valueB, valueC - this way, if a signature of
ob->doSomething(x, vallue, y, z) changes, you'll only have to change it in one place, not 3 or more...

but hey, that's a 'different opinion', let's just do copy-and-paste.

well, what can I say. Symfony positions itself as a high-quality framework, but what I see in code now and there tells a different story.  I am shocked I have to explain / advocate simple, obvious things - yet without any success...

as a senior developer, who does a lot code reviews daily, I would never ever allow the original code into production.

okay now, I'm fed enough and really tired advocating myself. keep on with your great code, folks!

**Pull request closed without merging**
