### PR TITLE
Add smsapi-notifier recipe

### PR DESCRIPTION
**Pull request by szepczynski**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...    

add recipe for smsapi-notifier, details here: https://github.com/symfony/symfony/pull/36940

### CODE REVIEW

**Comment by stof** [comment]
5.1 is in feature freeze (the stable release will be in a few days). So this new bridge will only exist in 5.2+

**Comment by szepczynski** [comment]
Ok, i moved it to 5.2

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Comment by fabpot** [comment]
@symfony-flex-server review again please

**Pull request merged**
