### PR TITLE
Document the special %generate(secret)% env var value

### PR DESCRIPTION
**Pull request by javiereguiluz**
Some recipes are starting to use this feature (see https://github.com/symfony/recipes-contrib/pull/5/files) so let's document it.

### CODE REVIEW

**Comment by Pierstoval** [comment]
It is a Flex feature or a Symfony feature?

**Comment by stof** [comment]
it is a Flex feature. It will replace it by a random value when editing the .env file

**Comment by javiereguiluz** [comment]
@Pierstoval in #34 Fabien removed most references to the "Flex" name, so I thought it was a good idea to not mention it. But I've reworded to not mention neither Symfony nor Flex.

**Comment by Pierstoval** [comment]
Yeah, because there's a difference between Symfony (the framework) and Symfony Flex (the package auto-configurator), and the server behind all of this that does the validation 😆 Lots of new cool stuff!

**Comment by fabpot** [comment]
Thank you @javiereguiluz.

**Pull request closed without merging**
