### PR TITLE
Allow missing APP_ENV in .env.local.php

### PR DESCRIPTION
**Pull request by nicolas-grekas**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | -

Reported by @bendavies

### CODE REVIEW

**Comment by bendavies** [comment]
Thanks!

**Comment by bendavies** [comment]
hmm no, this is no good actually.

I'm not really sure what https://github.com/symfony/recipes/pull/647 was trying to solve, but it https://github.com/symfony/recipes/pull/647 + this PR break this workflow:
```
## DotEnv not installed
rm .env
echo '<?php return [];' > .env.local.php
APP_ENV=prod bin/console
```

This errors because this comparison fails:
```
($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? $env['APP_ENV'] ?? null) === ($env['APP_ENV'] ?? null)
// ->
prod === null = false
```

As above, I don't know how to fix this because I honestly can't work out what https://github.com/symfony/recipes/pull/647 was trying to achieve.
@nicolas-grekas can you advise?

Thanks.

**Comment by guilliamxavier** [comment]
<sup>(FTR: `syntax error, unexpected ')'` fixed in #720 and #723)</sup>

@bendavies: As I understand it, the purpose of #647 was to have e.g. `APP_ENV=test bin/console` always load `.env.test` even if `.env.local.php` exists [and contains `'APP_ENV' => 'prod'`].

But maybe it should not have been merged, because #501 clearly said "When `.env.local.php` is found, other .env files are ignored" and [the docs](https://symfony.com/doc/4.4/configuration.html#configuring-environment-variables-in-production) say "After running this command [`composer dump-env prod`], Symfony will load the `.env.local.php` file to get the environment variables and will not spend time parsing the `.env` files".

@nicolas-grekas what do you think, should #647 be reverted?

Besides, Ben's workflow highlights a question: if you only use real environment variables and don't use any `.env` file nor the `Dotenv` component [in prod], you are still required to either create an "empty" (`<?php return [];`) `.env.local.php` or install `symfony/dotenv`, even though you actually don't need them?

**Comment by nicolas-grekas** [comment]
@guilliamxavier see https://github.com/symfony/recipes/pull/719

> if you only use real environment variables and don't use any .env file nor the Dotenv component [in prod], you are still required to either create an empty .env.local.php

yes, that's desired as that's the best tradeoff for everyone.

**Comment by guilliamxavier** [comment]
@nicolas-grekas: 719 was this PR, I guess your meant #727. Indeed, I had missed it (thanks!). But then I also found #574, to which you answered:

> As you spotted, .env.local.php freezes .env files. As such and on purpose, it's only for prod-like needs. Don't use it in test nor dev.

so isn't it paradoxical that you accepted #647 (~ six months later)? The docs aren't crystal clear either, so what is the actually intended behavior?

(As for the second question, thanks for the confirmation. I also found #529.)

**Comment by nicolas-grekas** [comment]
> I guess your meant #727

correct, updated

> isn't it paradoxical that you accepted #647

**Pull request merged**
