### PR TITLE
mailer: missing xsl extension

### PR DESCRIPTION
**Pull request by COil**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...

For the full explanation, check out this ticket please (or i'll copy/paste)

https://github.com/dunglas/symfony-docker/pull/308

### CODE REVIEW

**Comment by maxhelias** [comment]
Shouldn't it be more on the package `twig/inky-extra` ?

**Comment by stof** [comment]
or even better: on a recipe for the Inky package

**Comment by fabpot** [comment]
It's already the case: see https://github.com/lorenzo/pinky/pull/10/files

**Comment by maxhelias** [comment]
@fabpot This is more about installing the extension in the dockerfile with a recipe :)

**Comment by fabpot** [comment]
But then, we need a standardized way of doing it.

**Pull request closed without merging**
