### PR TITLE
[doctrine-bundle] Add DATABASE_DRIVER in .env

### PR DESCRIPTION
**Pull request by mazarini**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | doctrine/doctrine-bundle#626    

Allow to share one config and use differents databases with .env.local.
(add DATABASE_SERVER_VERSION too)

### CODE REVIEW

**Comment by mazarini** [comment]
Test OK for "composer require orm" instead of "composer require symfony/doctrine-bundle".

**Comment by BoShurik** [comment]
See https://github.com/symfony/recipes/pull/462

**Comment by mazarini** [comment]
An other option is to add a fallback in doctrine.yaml for DATABASE_SERVER_VERSION and DATABASE_DRIVER. So we can put it as comment in .env and set it only if needed.
Nothing change if it's not use.

**Comment by weaverryan** [comment]
This issue is tough. There are two problems with your approach:

1) `DATABASE_SERVER_VERSION` should not be something that is allowed to change (as an env var). Doing this might mean that one developer (with one version) generates migrations using newer SQL features than our supported on production's true server version.

2) The `default_table_options` are still in the YAML file, and are specific to MySQL.

Cheers!

**Pull request closed without merging**
