### PR TITLE
Fix PHPUnit xsd version

### PR DESCRIPTION
**Pull request by Pierstoval**
The base supported version is ~4.7~ 6.1 as specified in the ~directory~ version aliases

### CODE REVIEW

**Comment by sstok** [comment]
Note that PHPUnit doesn't actually use this uri for validating, it's mainly for IDE auto suggest 😛

**Comment by Pierstoval** [comment]
Yep, but still, _consistency_, you know 😜

**Comment by fabpot** [comment]
What about doing it the other way and bump the version to the max in the XSD? That way, you have autocompletion for everything supported.

**Comment by Pierstoval** [comment]
You're right @fabpot, updated the PR

**Comment by fabpot** [comment]
Thank you @Pierstoval.

**Pull request merged**
