### PR TITLE
Remove api-platform/core recipes

### PR DESCRIPTION
**Pull request by fck-ms**
A "composer require" of a library should never lead to changes in the configuration of an application. This is only acceptable behavior for bundles and packs. As api-platform/core is a library (according to the composer.json file) there should be no recipes.

### CODE REVIEW

**Comment by chalasr** [comment]
Actually, the recipe wires the Symfony bundle provided by (and embedded in) the api-platform/core package. Cllosing for this reason. Thanks

**Comment by fck-ms** [comment]
Then the bundle should be a separate package and recipes should be added for the bundle package. At this moment the api-platform/core package is published as a library and there shouldn't be any recipes for library packages.

**Comment by chalasr** [comment]
Possibly yes, please consider discussing this on the api-platform/core repository.

**Comment by fck-ms** [comment]
https://github.com/api-platform/core/issues/5357

**Pull request closed without merging**
