### PR TITLE
Add receipts for twig/*-extra to allow these packages to 'just work'

### PR DESCRIPTION
**Pull request by mcfedr**
| Q             | A
| ------------- | ---
| License       | MIT
| Doc issue/PR  | symfony/symfony-docs#...

### CODE REVIEW

**Comment by Pierstoval** [comment]
If you use the TwigExtraBundle, that's already the case, it already does the magic for you: https://github.com/twigphp/twig-extra-bundle/blob/2.x/src/Extensions.php

**Comment by stof** [comment]
These recipes will cause issues when installing twig-extra-bundle, because extensions will then be registered twice.

**Comment by fabpot** [comment]
As already mentioned, the Twig Extra bundle should be used instead.

**Comment by mcfedr** [comment]
ah, wow, i didnt find that anywhere, i guess some links needed in the twig docs. 

Is it possible to have the receipe just do nothing when that bundle is installed? might be a nice way of avoiding a bundle that is basically a receipe, and also lettting me easily just use one of these.

**Comment by Pierstoval** [comment]
> Is it possible to have the receipe just do nothing when that bundle is installed? might be a nice way of avoiding a bundle that is basically a receipe, and also lettting me easily just use one of these.

Well, that's what the bundle actually does 😉  

The bundle does not require the twig extra packages. If the package is installed, the bundle registers it in the container.

**Pull request closed without merging**
